// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {content} from '../models';
import {context} from '../models';

export function BackupSave(arg1:string):Promise<string>;

export function DeleteSave(arg1:string):Promise<void>;

export function ExportSave(arg1:string,arg2:string):Promise<string>;

export function GetCustomIconPath(arg1:string,arg2:string):Promise<string>;

export function GetInstanceVisual(arg1:string,arg2:string):Promise<content.GameInstanceVisual>;

export function ReadMods(arg1:string):Promise<Array<content.GameContentEntry>>;

export function ReadResourcePacks(arg1:string):Promise<Array<content.GameContentEntry>>;

export function ReadSaves(arg1:string):Promise<Array<content.GameContentEntry>>;

export function ReadShaders(arg1:string):Promise<Array<content.GameContentEntry>>;

export function RemoveCustomIcon(arg1:string,arg2:string):Promise<boolean>;

export function SetCustomIcon(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleContentEntry(arg1:string,arg2:boolean):Promise<void>;
