// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupSave(arg1) {
  return window['go']['bindings']['ContentAPI']['BackupSave'](arg1);
}

export function DeleteSave(arg1) {
  return window['go']['bindings']['ContentAPI']['DeleteSave'](arg1);
}

export function ExportSave(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['ExportSave'](arg1, arg2);
}

export function GetCustomIconPath(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['GetCustomIconPath'](arg1, arg2);
}

export function GetInstanceVisual(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['GetInstanceVisual'](arg1, arg2);
}

export function ReadMods(arg1) {
  return window['go']['bindings']['ContentAPI']['ReadMods'](arg1);
}

export function ReadResourcePacks(arg1) {
  return window['go']['bindings']['ContentAPI']['ReadResourcePacks'](arg1);
}

export function ReadSaves(arg1) {
  return window['go']['bindings']['ContentAPI']['ReadSaves'](arg1);
}

export function ReadShaders(arg1) {
  return window['go']['bindings']['ContentAPI']['ReadShaders'](arg1);
}

export function RemoveCustomIcon(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['RemoveCustomIcon'](arg1, arg2);
}

export function SetCustomIcon(arg1, arg2, arg3) {
  return window['go']['bindings']['ContentAPI']['SetCustomIcon'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['bindings']['ContentAPI']['Startup'](arg1);
}

export function ToggleContentEntry(arg1, arg2) {
  return window['go']['bindings']['ContentAPI']['ToggleContentEntry'](arg1, arg2);
}
