// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentTrack() {
  return window['go']['bindings']['MusicAPI']['GetCurrentTrack']();
}

export function GetMusicFolderPath() {
  return window['go']['bindings']['MusicAPI']['GetMusicFolderPath']();
}

export function GetMusicLastError() {
  return window['go']['bindings']['MusicAPI']['GetMusicLastError']();
}

export function GetMusicPlaybackMode() {
  return window['go']['bindings']['MusicAPI']['GetMusicPlaybackMode']();
}

export function GetMusicSortMode() {
  return window['go']['bindings']['MusicAPI']['GetMusicSortMode']();
}

export function GetMusicTracks() {
  return window['go']['bindings']['MusicAPI']['GetMusicTracks']();
}

export function GetMusicVolume() {
  return window['go']['bindings']['MusicAPI']['GetMusicVolume']();
}

export function GetPlaybackDuration() {
  return window['go']['bindings']['MusicAPI']['GetPlaybackDuration']();
}

export function GetPlaybackPosition() {
  return window['go']['bindings']['MusicAPI']['GetPlaybackPosition']();
}

export function GetPlaybackState() {
  return window['go']['bindings']['MusicAPI']['GetPlaybackState']();
}

export function GetPlaylist() {
  return window['go']['bindings']['MusicAPI']['GetPlaylist']();
}

export function GetSortedMusicTracks(arg1) {
  return window['go']['bindings']['MusicAPI']['GetSortedMusicTracks'](arg1);
}

export function NextTrack() {
  return window['go']['bindings']['MusicAPI']['NextTrack']();
}

export function NotifyTrackFinished() {
  return window['go']['bindings']['MusicAPI']['NotifyTrackFinished']();
}

export function PausePlayback() {
  return window['go']['bindings']['MusicAPI']['PausePlayback']();
}

export function PlayTrack(arg1) {
  return window['go']['bindings']['MusicAPI']['PlayTrack'](arg1);
}

export function PreviousTrack() {
  return window['go']['bindings']['MusicAPI']['PreviousTrack']();
}

export function ReportPlaybackProgress(arg1, arg2) {
  return window['go']['bindings']['MusicAPI']['ReportPlaybackProgress'](arg1, arg2);
}

export function ResumePlayback() {
  return window['go']['bindings']['MusicAPI']['ResumePlayback']();
}

export function ScanMusicLibrary() {
  return window['go']['bindings']['MusicAPI']['ScanMusicLibrary']();
}

export function SearchMusicTracks(arg1) {
  return window['go']['bindings']['MusicAPI']['SearchMusicTracks'](arg1);
}

export function SeekPlayback(arg1) {
  return window['go']['bindings']['MusicAPI']['SeekPlayback'](arg1);
}

export function SetMusicFolder(arg1) {
  return window['go']['bindings']['MusicAPI']['SetMusicFolder'](arg1);
}

export function SetMusicPlaybackMode(arg1) {
  return window['go']['bindings']['MusicAPI']['SetMusicPlaybackMode'](arg1);
}

export function SetMusicSortMode(arg1) {
  return window['go']['bindings']['MusicAPI']['SetMusicSortMode'](arg1);
}

export function SetMusicVolume(arg1) {
  return window['go']['bindings']['MusicAPI']['SetMusicVolume'](arg1);
}

export function SetPlaylist(arg1) {
  return window['go']['bindings']['MusicAPI']['SetPlaylist'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['MusicAPI']['Startup'](arg1);
}

export function StopPlayback() {
  return window['go']['bindings']['MusicAPI']['StopPlayback']();
}
