// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {context} from '../models';

export function GetUnreachableStatus(arg1:string):Promise<network.MinecraftServerStatus>;

export function ParseServerAddress(arg1:string):Promise<string>;

export function PingServer(arg1:string,arg2:number):Promise<network.MinecraftServerStatus>;

export function Startup(arg1:context.Context):Promise<void>;
