// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {world} from '../models';
import {context} from '../models';

export function GetRecentWorlds(arg1:number):Promise<Array<world.WorldInfo>>;

export function Startup(arg1:context.Context):Promise<void>;
