// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentWorlds(arg1) {
  return window['go']['bindings']['WorldAPI']['GetRecentWorlds'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['WorldAPI']['Startup'](arg1);
}
