// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function AddAccount(arg1:auth.LaunchAccount):Promise<void>;

export function AuthlibLogin(arg1:string,arg2:string,arg3:string,arg4:string):Promise<auth.AuthlibLoginResult>;

export function CancelMicrosoftLogin():Promise<void>;

export function CreateOfflineAccount(arg1:string):Promise<auth.LaunchAccount>;

export function FindAccountByStableKey(arg1:string):Promise<auth.LaunchAccount>;

export function GetAccountStableKey(arg1:auth.LaunchAccount):Promise<string>;

export function GetAccounts():Promise<Array<auth.LaunchAccount>>;

export function GetAuthlibClientToken():Promise<string>;

export function GetAvatarUrl(arg1:string):Promise<string>;

export function GetOfflineSkinCatalog():Promise<Array<bindings.OfflineSkinChoice>>;

export function GetSelectedAccount():Promise<auth.LaunchAccount>;

export function GetSkinUrl(arg1:string):Promise<string>;

export function HasOfflineName(arg1:string):Promise<boolean>;

export function IsSecretProtectionAvailable():Promise<boolean>;

export function LoginMicrosoft():Promise<auth.MicrosoftAccount>;

export function MoveAccountToTop(arg1:auth.LaunchAccount):Promise<void>;

export function ProtectSecret(arg1:string):Promise<string>;

export function RefreshMicrosoftAccount(arg1:auth.MicrosoftAccount):Promise<auth.MicrosoftAccount>;

export function ReloadAccounts():Promise<void>;

export function RemoveAccount(arg1:auth.LaunchAccount):Promise<void>;

export function ResolveAuthlibServer(arg1:string):Promise<auth.AuthlibServerInfo>;

export function ResolveComponentDisplayAccount(arg1:string):Promise<auth.LaunchAccount>;

export function SaveAccounts():Promise<void>;

export function SelectAccountByStableKey(arg1:string):Promise<boolean>;

export function SetComponentDisplayAccountKey(arg1:string,arg2:string):Promise<void>;

export function SetOfflineSkin(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UnprotectSecret(arg1:string):Promise<string>;

export function UpdateAuthlibAccount(arg1:auth.LaunchAccount,arg2:auth.AuthlibCredential):Promise<void>;

export function UpdateMicrosoftAccount(arg1:auth.LaunchAccount,arg2:auth.MicrosoftAccount):Promise<void>;

export function UpdateOfflineSkin(arg1:auth.LaunchAccount,arg2:string):Promise<void>;

export function UploadSkin(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ValidateMicrosoftAccount(arg1:auth.MicrosoftAccount):Promise<auth.MicrosoftAccount>;

export function ValidateOrRefreshAuthlib(arg1:auth.AuthlibCredential,arg2:string):Promise<string>;
