// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddJava(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['AddJava'](arg1, arg2);
}

export function AddProfileFolder(arg1) {
  return window['go']['bindings']['ConfigAPI']['AddProfileFolder'](arg1);
}

export function ClearGameDirectory() {
  return window['go']['bindings']['ConfigAPI']['ClearGameDirectory']();
}

export function ClearJava() {
  return window['go']['bindings']['ConfigAPI']['ClearJava']();
}

export function ClearValue(arg1) {
  return window['go']['bindings']['ConfigAPI']['ClearValue'](arg1);
}

export function GetDefaultStorageDirectory() {
  return window['go']['bindings']['ConfigAPI']['GetDefaultStorageDirectory']();
}

export function GetDefaultVersionIsolation() {
  return window['go']['bindings']['ConfigAPI']['GetDefaultVersionIsolation']();
}

export function GetGameDirectory() {
  return window['go']['bindings']['ConfigAPI']['GetGameDirectory']();
}

export function GetInstanceIconOverride(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['GetInstanceIconOverride'](arg1, arg2);
}

export function GetJavaExecutable() {
  return window['go']['bindings']['ConfigAPI']['GetJavaExecutable']();
}

export function GetJavaPaths() {
  return window['go']['bindings']['ConfigAPI']['GetJavaPaths']();
}

export function GetJavaVersion() {
  return window['go']['bindings']['ConfigAPI']['GetJavaVersion']();
}

export function GetLegacyDefaultStorageDirectory() {
  return window['go']['bindings']['ConfigAPI']['GetLegacyDefaultStorageDirectory']();
}

export function GetProfileFolders() {
  return window['go']['bindings']['ConfigAPI']['GetProfileFolders']();
}

export function GetStorageDirectory() {
  return window['go']['bindings']['ConfigAPI']['GetStorageDirectory']();
}

export function GetUserHome() {
  return window['go']['bindings']['ConfigAPI']['GetUserHome']();
}

export function GetValue(arg1) {
  return window['go']['bindings']['ConfigAPI']['GetValue'](arg1);
}

export function GetVerifyFilesBeforeLaunch() {
  return window['go']['bindings']['ConfigAPI']['GetVerifyFilesBeforeLaunch']();
}

export function GetVersionProfile(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['GetVersionProfile'](arg1, arg2);
}

export function LoadGlobalLaunchSettings() {
  return window['go']['bindings']['ConfigAPI']['LoadGlobalLaunchSettings']();
}

export function MigrateRenamedVersion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bindings']['ConfigAPI']['MigrateRenamedVersion'](arg1, arg2, arg3, arg4, arg5);
}

export function NewGameVersionProfile() {
  return window['go']['bindings']['ConfigAPI']['NewGameVersionProfile']();
}

export function PathsEqualNormalized(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['PathsEqualNormalized'](arg1, arg2);
}

export function RemoveJava(arg1) {
  return window['go']['bindings']['ConfigAPI']['RemoveJava'](arg1);
}

export function RemoveProfileFolder(arg1) {
  return window['go']['bindings']['ConfigAPI']['RemoveProfileFolder'](arg1);
}

export function SaveDefaultVersionIsolation(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveDefaultVersionIsolation'](arg1);
}

export function SaveGameDirectory(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveGameDirectory'](arg1);
}

export function SaveGlobalLaunchSettings(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveGlobalLaunchSettings'](arg1);
}

export function SaveGlobalWindowSize(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['SaveGlobalWindowSize'](arg1, arg2);
}

export function SaveInstanceIconOverride(arg1, arg2, arg3) {
  return window['go']['bindings']['ConfigAPI']['SaveInstanceIconOverride'](arg1, arg2, arg3);
}

export function SaveJava(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['SaveJava'](arg1, arg2);
}

export function SaveVerifyFilesBeforeLaunch(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveVerifyFilesBeforeLaunch'](arg1);
}

export function SaveVersionProfile(arg1) {
  return window['go']['bindings']['ConfigAPI']['SaveVersionProfile'](arg1);
}

export function SetPrimaryJava(arg1) {
  return window['go']['bindings']['ConfigAPI']['SetPrimaryJava'](arg1);
}

export function SetStorageDirectory(arg1) {
  return window['go']['bindings']['ConfigAPI']['SetStorageDirectory'](arg1);
}

export function SetValue(arg1, arg2) {
  return window['go']['bindings']['ConfigAPI']['SetValue'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['bindings']['ConfigAPI']['Startup'](arg1);
}
