// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDownloadSettings() {
  return window['go']['bindings']['DownloadAPI']['ApplyDownloadSettings']();
}

export function ApplyVersionFilter(arg1, arg2) {
  return window['go']['bindings']['DownloadAPI']['ApplyVersionFilter'](arg1, arg2);
}

export function CancelDownload() {
  return window['go']['bindings']['DownloadAPI']['CancelDownload']();
}

export function CreateDefaultInstanceName(arg1, arg2, arg3) {
  return window['go']['bindings']['DownloadAPI']['CreateDefaultInstanceName'](arg1, arg2, arg3);
}

export function DeleteJavaRuntime(arg1) {
  return window['go']['bindings']['DownloadAPI']['DeleteJavaRuntime'](arg1);
}

export function DownloadFileToInstance(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['DownloadAPI']['DownloadFileToInstance'](arg1, arg2, arg3, arg4);
}

export function DownloadFileToPath(arg1, arg2) {
  return window['go']['bindings']['DownloadAPI']['DownloadFileToPath'](arg1, arg2);
}

export function DownloadModpackFile(arg1, arg2, arg3) {
  return window['go']['bindings']['DownloadAPI']['DownloadModpackFile'](arg1, arg2, arg3);
}

export function GetActiveDownloadSourceName() {
  return window['go']['bindings']['DownloadAPI']['GetActiveDownloadSourceName']();
}

export function GetAllDownloadSources() {
  return window['go']['bindings']['DownloadAPI']['GetAllDownloadSources']();
}

export function GetCurrentDownloadSnapshot() {
  return window['go']['bindings']['DownloadAPI']['GetCurrentDownloadSnapshot']();
}

export function GetFabricVersions(arg1) {
  return window['go']['bindings']['DownloadAPI']['GetFabricVersions'](arg1);
}

export function GetFallbackDownloadSourceName() {
  return window['go']['bindings']['DownloadAPI']['GetFallbackDownloadSourceName']();
}

export function GetForgeVersions(arg1) {
  return window['go']['bindings']['DownloadAPI']['GetForgeVersions'](arg1);
}

export function GetInstalledJavaRuntimes() {
  return window['go']['bindings']['DownloadAPI']['GetInstalledJavaRuntimes']();
}

export function GetJavaPlatformDisplayName() {
  return window['go']['bindings']['DownloadAPI']['GetJavaPlatformDisplayName']();
}

export function GetJavaRuntimeDirectory() {
  return window['go']['bindings']['DownloadAPI']['GetJavaRuntimeDirectory']();
}

export function GetJavaVendorDisplayName(arg1) {
  return window['go']['bindings']['DownloadAPI']['GetJavaVendorDisplayName'](arg1);
}

export function GetModLoaderVersions(arg1, arg2) {
  return window['go']['bindings']['DownloadAPI']['GetModLoaderVersions'](arg1, arg2);
}

export function GetNeoForgeVersions(arg1) {
  return window['go']['bindings']['DownloadAPI']['GetNeoForgeVersions'](arg1);
}

export function GetParallelDownloads() {
  return window['go']['bindings']['DownloadAPI']['GetParallelDownloads']();
}

export function GetQuiltVersions(arg1) {
  return window['go']['bindings']['DownloadAPI']['GetQuiltVersions'](arg1);
}

export function GetVersions() {
  return window['go']['bindings']['DownloadAPI']['GetVersions']();
}

export function InstallJavaRuntime(arg1) {
  return window['go']['bindings']['DownloadAPI']['InstallJavaRuntime'](arg1);
}

export function InstallModpackToInstance(arg1, arg2) {
  return window['go']['bindings']['DownloadAPI']['InstallModpackToInstance'](arg1, arg2);
}

export function IsDownloadPaused() {
  return window['go']['bindings']['DownloadAPI']['IsDownloadPaused']();
}

export function NormalizeBmclNeoForgeVersion(arg1) {
  return window['go']['bindings']['DownloadAPI']['NormalizeBmclNeoForgeVersion'](arg1);
}

export function ParseJavaVendor(arg1) {
  return window['go']['bindings']['DownloadAPI']['ParseJavaVendor'](arg1);
}

export function PauseDownload() {
  return window['go']['bindings']['DownloadAPI']['PauseDownload']();
}

export function QueryAvailableJavaVersions(arg1) {
  return window['go']['bindings']['DownloadAPI']['QueryAvailableJavaVersions'](arg1);
}

export function ReadModpackRequirements(arg1) {
  return window['go']['bindings']['DownloadAPI']['ReadModpackRequirements'](arg1);
}

export function ResolveContentDirectoryForInstance(arg1, arg2, arg3) {
  return window['go']['bindings']['DownloadAPI']['ResolveContentDirectoryForInstance'](arg1, arg2, arg3);
}

export function ResumeDownload() {
  return window['go']['bindings']['DownloadAPI']['ResumeDownload']();
}

export function SaveActiveDownloadSource(arg1) {
  return window['go']['bindings']['DownloadAPI']['SaveActiveDownloadSource'](arg1);
}

export function SaveFallbackDownloadSource(arg1) {
  return window['go']['bindings']['DownloadAPI']['SaveFallbackDownloadSource'](arg1);
}

export function SaveParallelDownloads(arg1) {
  return window['go']['bindings']['DownloadAPI']['SaveParallelDownloads'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['bindings']['DownloadAPI']['StartDownload'](arg1);
}

export function StartModLoaderDownload(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['DownloadAPI']['StartModLoaderDownload'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['bindings']['DownloadAPI']['Startup'](arg1);
}
