// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {download} from '../models';
import {context} from '../models';

export function ApplyDownloadSettings():Promise<void>;

export function ApplyVersionFilter(arg1:Array<models.MinecraftVersion>,arg2:string):Promise<Array<models.MinecraftVersion>>;

export function CancelDownload():Promise<boolean>;

export function CreateDefaultInstanceName(arg1:download.ModLoaderType,arg2:string,arg3:string):Promise<string>;

export function DeleteJavaRuntime(arg1:string):Promise<void>;

export function DownloadFileToInstance(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function DownloadFileToPath(arg1:string,arg2:string):Promise<void>;

export function DownloadModpackFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActiveDownloadSourceName():Promise<string>;

export function GetAllDownloadSources():Promise<Array<download.DownloadSource>>;

export function GetCurrentDownloadSnapshot():Promise<download.GameDownloadSnapshot>;

export function GetFabricVersions(arg1:string):Promise<Array<download.ModLoaderVersion>>;

export function GetFallbackDownloadSourceName():Promise<string>;

export function GetForgeVersions(arg1:string):Promise<Array<download.ModLoaderVersion>>;

export function GetInstalledJavaRuntimes():Promise<Array<download.InstalledJavaRuntime>>;

export function GetJavaPlatformDisplayName():Promise<string>;

export function GetJavaRuntimeDirectory():Promise<string>;

export function GetJavaVendorDisplayName(arg1:download.JavaVendor):Promise<string>;

export function GetModLoaderVersions(arg1:download.ModLoaderType,arg2:string):Promise<Array<download.ModLoaderVersion>>;

export function GetNeoForgeVersions(arg1:string):Promise<Array<download.ModLoaderVersion>>;

export function GetParallelDownloads():Promise<number>;

export function GetQuiltVersions(arg1:string):Promise<Array<download.ModLoaderVersion>>;

export function GetVersions():Promise<Array<models.MinecraftVersion>>;

export function InstallJavaRuntime(arg1:download.JavaDownloadCandidate):Promise<download.InstalledJavaRuntime>;

export function InstallModpackToInstance(arg1:string,arg2:string):Promise<download.ModpackInstallResult>;

export function IsDownloadPaused():Promise<boolean>;

export function NormalizeBmclNeoForgeVersion(arg1:string):Promise<string>;

export function ParseJavaVendor(arg1:string):Promise<download.JavaVendor|boolean>;

export function PauseDownload():Promise<boolean>;

export function QueryAvailableJavaVersions(arg1:download.JavaVendor):Promise<Array<download.JavaDownloadCandidate>>;

export function ReadModpackRequirements(arg1:string):Promise<download.ModpackRequirements>;

export function ResolveContentDirectoryForInstance(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ResumeDownload():Promise<boolean>;

export function SaveActiveDownloadSource(arg1:download.DownloadSource):Promise<void>;

export function SaveFallbackDownloadSource(arg1:download.DownloadSource):Promise<void>;

export function SaveParallelDownloads(arg1:number):Promise<void>;

export function StartDownload(arg1:models.MinecraftVersion):Promise<boolean>;

export function StartModLoaderDownload(arg1:models.MinecraftVersion,arg2:download.ModLoaderVersion,arg3:string,arg4:boolean):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;
