// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDirectory(arg1) {
  return window['go']['bindings']['LauncherAPI']['DeleteDirectory'](arg1);
}

export function DetectJavaMajorVersion(arg1) {
  return window['go']['bindings']['LauncherAPI']['DetectJavaMajorVersion'](arg1);
}

export function GetLaunchSnapshot() {
  return window['go']['bindings']['LauncherAPI']['GetLaunchSnapshot']();
}

export function GetLogText() {
  return window['go']['bindings']['LauncherAPI']['GetLogText']();
}

export function GetManualMaximumMemoryMb() {
  return window['go']['bindings']['LauncherAPI']['GetManualMaximumMemoryMb']();
}

export function GetMemoryDecision(arg1) {
  return window['go']['bindings']['LauncherAPI']['GetMemoryDecision'](arg1);
}

export function GetMemorySliderMaximum() {
  return window['go']['bindings']['LauncherAPI']['GetMemorySliderMaximum']();
}

export function GetSystemMemory() {
  return window['go']['bindings']['LauncherAPI']['GetSystemMemory']();
}

export function IsAutomaticMemoryAdjustmentEnabled() {
  return window['go']['bindings']['LauncherAPI']['IsAutomaticMemoryAdjustmentEnabled']();
}

export function Launch(arg1, arg2) {
  return window['go']['bindings']['LauncherAPI']['Launch'](arg1, arg2);
}

export function RedactLogSecrets(arg1) {
  return window['go']['bindings']['LauncherAPI']['RedactLogSecrets'](arg1);
}

export function SaveManualMaximumMemoryMb(arg1) {
  return window['go']['bindings']['LauncherAPI']['SaveManualMaximumMemoryMb'](arg1);
}

export function SetAutomaticMemoryAdjustmentEnabled(arg1) {
  return window['go']['bindings']['LauncherAPI']['SetAutomaticMemoryAdjustmentEnabled'](arg1);
}

export function Startup(arg1) {
  return window['go']['bindings']['LauncherAPI']['Startup'](arg1);
}

export function StopGame() {
  return window['go']['bindings']['LauncherAPI']['StopGame']();
}
