// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectExportContent(arg1) {
  return window['go']['bindings']['ModpackAPI']['CollectExportContent'](arg1);
}

export function ExportModpack(arg1, arg2, arg3) {
  return window['go']['bindings']['ModpackAPI']['ExportModpack'](arg1, arg2, arg3);
}

export function GetExportProfilePath(arg1) {
  return window['go']['bindings']['ModpackAPI']['GetExportProfilePath'](arg1);
}

export function LoadExportProfile(arg1) {
  return window['go']['bindings']['ModpackAPI']['LoadExportProfile'](arg1);
}

export function NewExportOptions() {
  return window['go']['bindings']['ModpackAPI']['NewExportOptions']();
}

export function SaveExportProfile(arg1, arg2) {
  return window['go']['bindings']['ModpackAPI']['SaveExportProfile'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['bindings']['ModpackAPI']['Startup'](arg1);
}
