// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMemorySnapshot() {
  return window['go']['bindings']['MonitorAPI']['GetMemorySnapshot']();
}

export function Startup(arg1) {
  return window['go']['bindings']['MonitorAPI']['Startup'](arg1);
}
