// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitoring} from '../models';
import {context} from '../models';

export function GetMemorySnapshot():Promise<monitoring.MemorySnapshot>;

export function Startup(arg1:context.Context):Promise<void>;
