// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {music} from '../models';
import {context} from '../models';

export function GetCurrentTrack():Promise<music.MusicTrack>;

export function GetMusicFolderPath():Promise<string>;

export function GetMusicLastError():Promise<string>;

export function GetMusicPlaybackMode():Promise<music.PlaybackMode>;

export function GetMusicSortMode():Promise<music.MusicSortMode>;

export function GetMusicTracks():Promise<Array<music.MusicTrack>>;

export function GetMusicVolume():Promise<number>;

export function GetPlaybackDuration():Promise<number>;

export function GetPlaybackPosition():Promise<number>;

export function GetPlaybackState():Promise<music.PlaybackState>;

export function GetPlaylist():Promise<Array<music.MusicTrack>>;

export function GetSortedMusicTracks(arg1:music.MusicSortMode):Promise<Array<music.MusicTrack>>;

export function NextTrack():Promise<boolean>;

export function NotifyTrackFinished():Promise<void>;

export function PausePlayback():Promise<void>;

export function PlayTrack(arg1:music.MusicTrack):Promise<void>;

export function PreviousTrack():Promise<boolean>;

export function ReportPlaybackProgress(arg1:number,arg2:number):Promise<void>;

export function ResumePlayback():Promise<void>;

export function ScanMusicLibrary():Promise<void>;

export function SearchMusicTracks(arg1:string):Promise<Array<music.MusicTrack>>;

export function SeekPlayback(arg1:number):Promise<void>;

export function SetMusicFolder(arg1:string):Promise<void>;

export function SetMusicPlaybackMode(arg1:music.PlaybackMode):Promise<void>;

export function SetMusicSortMode(arg1:music.MusicSortMode):Promise<void>;

export function SetMusicVolume(arg1:number):Promise<void>;

export function SetPlaylist(arg1:Array<music.MusicTrack>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopPlayback():Promise<void>;
