// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUnreachableStatus(arg1) {
  return window['go']['bindings']['ServerAPI']['GetUnreachableStatus'](arg1);
}

export function ParseServerAddress(arg1) {
  return window['go']['bindings']['ServerAPI']['ParseServerAddress'](arg1);
}

export function PingServer(arg1, arg2) {
  return window['go']['bindings']['ServerAPI']['PingServer'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['bindings']['ServerAPI']['Startup'](arg1);
}
