// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1, arg2) {
  return window['go']['bindings']['SystemAPI']['AddLog'](arg1, arg2);
}

export function ClearLogs() {
  return window['go']['bindings']['SystemAPI']['ClearLogs']();
}

export function GetAppVersion() {
  return window['go']['bindings']['SystemAPI']['GetAppVersion']();
}

export function GetFormattedVersion() {
  return window['go']['bindings']['SystemAPI']['GetFormattedVersion']();
}

export function OpenInExplorer(arg1) {
  return window['go']['bindings']['SystemAPI']['OpenInExplorer'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['bindings']['SystemAPI']['OpenPath'](arg1);
}

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['SystemAPI']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory(arg1) {
  return window['go']['bindings']['SystemAPI']['SelectDirectory'](arg1);
}

export function SelectFile(arg1, arg2, arg3) {
  return window['go']['bindings']['SystemAPI']['SelectFile'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['bindings']['SystemAPI']['Startup'](arg1);
}

export function WriteLog(arg1, arg2) {
  return window['go']['bindings']['SystemAPI']['WriteLog'](arg1, arg2);
}
