// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddLog(arg1:string,arg2:string):Promise<boolean>;

export function ClearLogs():Promise<number>;

export function GetAppVersion():Promise<string>;

export function GetFormattedVersion():Promise<string>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function WriteLog(arg1:string,arg2:string):Promise<boolean>;
