<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.2-testplug.1</Version>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NyaLauncher.Plugin.Abstractions\NyaLauncher.Plugin.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Ai\" />
  </ItemGroup>

</Project>
